
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: node-hostname
  labels:
    app: node-hostname

spec:
  selector:
    matchLabels:
      app: node-hostname
      tier: frontend
  strategy:
    type: Recreate
  replicas: 5
  template:
    metadata:
      labels:
        app: node-hostname
        tier: frontend
    spec:
      containers:
      - image: pierangelo1982/node_hostname
        name: node-hostname
        ports:
        - containerPort: 3000
          name: node-hostname
    