apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql-node
spec:
  selector:
    matchLabels:
      app: mysql-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-node
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          #value: password
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql-node
        volumeMounts:
        - name: mysql-node-persistent-storage
          mountPath: /var/lib/mysql # percorso docker
      volumes:
      - name: mysql-node-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-node-pv-claim