apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app

spec:
  selector:
    matchLabels:
      app: node-app
      tier: frontend
  strategy:
    type: Recreate
  replicas: 5
  template:
    metadata:
      labels:
        app: node-app
        tier: frontend
    spec:
      containers:
      - image: pierangelo1982/node_mysql
        name: node-app
        ports:
        - containerPort: 3000
          name: node-app
        env:
            - name: DB_NAME
              value: "demo"
            - name: DB_USER
              value: "root"
            - name: DB_HOST
              value: mysql-node
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-secrets
                  key: mysql-password